---
dependency:
  name: galaxy
driver:
  name: digitalocean
lint:
  name: yamllint
platforms:
  - name:  test-webserver
    region_id: ams2
    image_id: ubuntu-16-04-x64
    size_id: s-1vcpu-1gb
    groups:
      - all
      - nfs-consumers
      - vpn-servers
      - webservers


  - name:  test-solr
    region_id: ams2
    image_id: ubuntu-18-04-x64
    size_id: s-1vcpu-1gb
    groups:
      - all
      - solrs

  - name:  test-nfs-server
    region_id: ams2
    image_id: ubuntu-18-04-x64
    size_id: s-1vcpu-2gb
    groups:
      - all
      - vpn-servers
      - nfs-servers

  - name:  test-mysql
    region_id: ams2
    image_id: 44038964
    size_id: s-6vcpu-16gb
    groups:
      - all
      - vpn-servers
      - mysqls

  - name: test-es-master
    region_id: ams2
    image_id: ubuntu-18-04-x64
    size_id: s-1vcpu-1gb
    groups:
      - all
      - vpn-servers
      - es-servers


provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH:
      $ephemeral_directory/roles/:../../roles/
  inventory:
    links:
      group_vars: ../../inventory/do/group_vars/
      host_vars: ../../inventory/common/host_vars/

  config_options:
    defaults:
      internal_poll_interval: 0.001
    ssh_connection:
      pipelining: True

  lint:
    name: ansible-lint
scenario:
  name: "do-cluster"
verifier:
  name: goss
  lint:
    name: yamllint
